extends:
  - "@commitlint/config-conventional"
rules:
  scope-enum:
    - 2
    - always
    - - auth
      - db
      - email
      - form
      - ui
      - validation
      - app
      - dashboard
      - config
      - deps
      - scripts
      - root